export default {
  "--- Getting Started": {
    type: "separator",
    title: "Getting Started",
  },
  index: "Introduction",
  installation: "Installation",
  "--- Examples": {
    type: "separator",
    title: "Examples",
  },
  uisample: "UI Sample",
  quizmenu: "Quiz Menu",
  worldlog: "World Log",
  "--- Layout": {
    type: "separator",
    title: "Layout",
  },
  canvas: "Canvas",
  sidebar: "Sidebar",
  "--- Components": {
    type: "separator",
    title: "Components",
  },
  button: "Button",
  text: "Text",
  toggle: "Toggle",
  card: "Card",
  dropdown: "Dropdown",
  inputfield: "InputField",
  progress: "Progress",
  radio: "Radio",
  scrollview: "Scroll View",
  scrollbar: "Scrollbar",
  slider: "Slider",
  span: "Span",
  switch: "Switch",
  "--- Components 2": {
    type: "separator",
    title: "Components 2",
  },
  dialog: "Dialog",
  toast: "Toast",
  "--- More": {
    type: "separator",
    title: "More",
  },
  github_link: {
    title: "Mono UI",
    href: "https://github.com/Limitex/mono-ui",
    newWindow: true,
  },
};
