export default {
  "--- Getting Started": {
    type: "separator",
    title: "Getting Started",
  },
  index: "Introduction",
  installation: "Installation",
  "--- Examples": {
    type: "separator",
    title: "Examples",
  },
  uisample: "UI Sample",
  quizmenu: "Quiz Menu",
  simplelog: "Simple Log",
  worldlog: "World Log",
  platformstatistics: "Platform Statistics",
  "--- Layout": {
    type: "separator",
    title: "Layout",
  },
  canvas: "Canvas",
  sidebar: "Sidebar",
  "--- Components": {
    type: "separator",
    title: "Components",
  },
  button: "Button",
  text: "Text",
  toggle: "Toggle",
  card: "Card",
  switch: "Switch",
  lucideicon: "Lucide Icon",
  "--- Input Controls": {
    type: "separator",
    title: "Input Controls",
  },
  dropdown: "Dropdown",
  inputfield: "InputField",
  slider: "Slider",
  "--- Navigation": {
    type: "separator",
    title: "Navigation",
  },
  scrollview: "Scroll View",
  scrollbar: "Scrollbar",
  carousel: "Carousel",
  "--- Utility": {
    type: "separator",
    title: "Utility",
  },
  progress: "Progress",
  span: "Span",
  separator: "Separator",
  table: "Table",
  "--- Loading": {
    type: "separator",
    title: "Loading",
  },
  loadingbar: "Loading Bar",
  loadingcircle: "Loading Circle",
  "--- Providers": {
    type: "separator",
    title: "Providers",
  },
  dialog: "Dialog",
  toast: "Toast",
  "--- More": {
    type: "separator",
    title: "More",
  },
  credit: "Credit",
  "--- Mono UI": {
    type: "separator",
  },
  github_link: {
    title: "Mono UI",
    href: "https://github.com/Limitex/mono-ui",
    newWindow: true,
  },
};
